# Generated by Django 4.1.2 on 2023-06-17 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0006_song_privacy_level_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='allowed_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 21, 43, 43, 757480)),
        ),
    ]
