# Generated by Django 4.1.2 on 2023-06-17 22:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_nation', '0007_song_allowed_emails_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 22, 11, 31, 822120)),
        ),
        migrations.RemoveField(
            model_name='song',
            name='allowed_emails',
        ),
        migrations.AddField(
            model_name='song',
            name='allowed_emails',
            field=models.ManyToManyField(blank=True, related_name='allowed_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
